apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-donation-service
  name: app-donation-service
  namespace: donation-service
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: app-donation-service
  template:
    metadata:
      labels:
        app: app-donation-service
    spec:
      containers:
        - name: app-donation-service
          image: 051688400625.dkr.ecr.us-east-1.amazonaws.com/solidarytech_donation-service:9eceed366f2c6ee3824f14b655942e4935b1b2c3
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 8082
            failureThreshold: 60
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: donation-db-secret
            - secretRef:
                name: donation-db-secret-host
